spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  datasource:
#    url: jdbc:h2:file:./db
#    url: jdbc:h2:mem:test
#    driverClassName: org.h2.Driver
#    username: test
#    password: test
    url: jdbc:postgresql://localhost:5432/liquibase-test
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true



